# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Teste da Action personalizada

# Nome dinâmico da execução atual
# github.actor -> usuário que disparou o workflow
run-name: ${{ github.actor }} está testando a Action personalizada

# Eventos que irão disparar o workflow
on:
  workflow_dispatch: # Permite disparar o workflow manualmente pela aba "Actions" do GitHub
  
# Lista de jobs do workflow
jobs: 

  # Nome interno do job
  test-action:

    # Máquina virtual utilizada pelo GitHub Actions
    runs-on: ubuntu-latest

    # Passos que o job executará em sequência
    steps:

      # Faz clone/download do repositório para dentro da máquina virtual
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      # Testa a action personalizada
      - name: Teste manual
        uses: ./03_actions/01_ola

